name: offline_videos_poc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  background_downloader: ^7.4.1
  video_player: ^2.7.0
  hive_flutter: ^1.1.0
  flutter:
    sdk: flutter
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
